project-includes = ["**/*.py", "**/*.pyi", "**/*.ipynb"]
project-excludes = [
    "**/build/**",
    "**/__pycache__/**",
    "**/*.egg-info/**",
    "**/.venv/**",
    "dopaminevla/models/siglino/build/**",
]

[errors]
implicit-import = false
bad-param-name-override = false
implicit-any = false
unannotated-return = false
unannotated-parameter = false
implicitly-defined-attribute = false

[[sub-config]]
matches = "tests/**"
[sub-config.errors]
unannotated-return = true
unannotated-parameter = true
implicit-any = false
