project-includes = ["**/*.py", "**/*.pyi", "**/*.ipynb"]
project-excludes = ["**/build/**", "**/__pycache__/**", "**/*.egg-info/**", "**/.venv/**"]

[errors]
implicit-import = false
implicit-any = true
bad-param-name-override = false
unannotated-return = true
unannotated-parameter = true
